Solution for 05-lection3-03-calendar
js-tasks-ru/htmlcss-20231027_andrey-shirling pull request #10
Opened 2023-12-03 15:53 UTC by io777

Solution for 05-lection3-03-calendar

2023-12-03 15:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-12-05 20:29 UTC, GSemikozov requested changes

2023-12-05 20:29 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding: 28px 36px;
`28 26 32` :)

2023-12-05 20:29 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    position: relative;
точно ли надо растягивать ширину/высоту и задавать relative?

2023-12-05 20:29 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    position: absolute;
а зачем?)

2025-12-02 14:42 UTC, closed without merging