add accordion style
js-tasks-ru/htmlcss-20231027_andrey-shirling pull request #5
Opened 2023-11-06 13:44 UTC by io777

Solution for 03-lection 02-accordion

2023-11-06 13:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-06 14:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-06 16:13 UTC, GSemikozov requested changes

2023-11-06 16:13 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
лишнее ограничение

2023-11-06 16:13 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    min-height: 72px;
лишнее

2023-11-06 16:13 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion {
судя по верстке - это все-таки не класс блока, а класс элемента блока - `accordion__item`

2023-11-06 16:13 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion_summary {
элементы пишем через `__`

2023-11-06 16:13 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-top: 24px;
нужно указать паддинги со всех сторон

2023-11-06 16:13 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin: 16px 49px 32px 32px;
паддинг

2023-11-06 16:13 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion_details {
см выше

2023-11-06 16:13 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion">
верстаем не 3 отдельных аккордиона, а 1, но - с 3 секциями

2023-11-08 05:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-08 08:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-08 08:06 UTC, io777 commented
1. Убрал ширину у .accordion__item, добавил блок .accordion с ограниченной шириной;
2. Убрал margin и добавил padding у .accordion__summary и .accordion__details;
3. Везде исправил написание блоком по БЭМ.

2023-11-08 09:25 UTC, GSemikozov requested changes

2023-11-08 09:25 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 0 24px 32px;
слева отступ тоже нужен

2023-11-08 09:25 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
фиксированную ширину нужно убрать

2023-11-08 11:19 UTC, io777 commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
убрал

2023-11-08 11:24 UTC, io777 commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 0 24px 32px;
добавил padding: 24px 49px 24px 32px;

2023-11-08 11:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-08 19:52 UTC, GSemikozov approved these changes

2023-11-08 19:52 UTC, merged