solution for 04-lection2/02-skeleton
js-tasks-ru/htmlcss-20231027_andrey-shirling pull request #7
Opened 2023-11-10 12:26 UTC by io777

Solution for 04-lection2/02-skeleton

2023-11-10 12:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-11 20:03 UTC, GSemikozov requested changes

2023-11-11 20:03 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.card {
блок карты описываем в блоке скелетон? однозначно что-то лишнее, так делать нельзя, надо удалить. Если это просто вспомогательные стили - то можно в отдельном файле стилей

2023-11-11 20:03 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__item--w20 {
а почему модификаторы через `--`?)

2023-11-11 20:03 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__item--w20 {
и лучше семантические классы, по типу .skeleton__item_small и тд

2023-11-12 06:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-12 06:08 UTC, io777 commented on 04-lection2/02-skeleton/skeleton.css
> +.card {
Да .card для удобства, удалил.

2023-11-12 06:10 UTC, io777 commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__item--w20 {
Переименовал на .skeleton__item_size_s и .skeleton__item_size_m

2023-11-12 06:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-12 13:53 UTC, GSemikozov approved these changes

2023-11-12 13:53 UTC, merged