Solution for 05-lection3-02-modal
js-tasks-ru/htmlcss-20231027_andrey-shirling pull request #9
Opened 2023-11-19 15:59 UTC by io777

Solution for 05-lection3-02-modal

2023-11-19 16:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-20 15:25 UTC, GSemikozov requested changes

2023-11-20 15:25 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +                <form action="" class="modal__form">
форму не верстаем, в рамках этой задачи - только заголовок и описании (ссылка на макет - в описании задачи)

2023-11-20 15:25 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +                <form action="" class="modal__form">
так все элементы формы будут лишними

2023-11-29 16:43 UTC, io777 commented on 05-lection3/02-modal/index.html
> +                <form action="" class="modal__form">
Убрал форму, добавил кнопку, добавил крестик, перверстал модальное окно.

2023-11-29 16:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-29 16:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-29 17:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-12-02 19:48 UTC, GSemikozov approved these changes

2023-12-02 19:48 UTC, merged